# 이전 강의 복습
def say_hello(user_name):
  print("hello", user_name)

say_hello("KARINA")      # 여기까지는 error가 발생하지 않는다
say_hello()              # 하지만 여기서는 error가 발생한다
                         # parameter 가 argument 를 기다리고 있는 상황인데
                         # () 안에 argument 를 보내지 못 했기 때문에 error 발생


# 이전 강의 복습
def say_hello(user_name):
  print("hello", user_name)

say_hello("KARINA")      # 여기까지는 error가 발생하지 않는다
say_hello()              # 하지만 여기서는 error가 발생한다
                         # parameter 가 argument 를 기다리고 있는 상황인데
                         # () 안에 argument 를 보내지 못 했기 때문에 error 발생


# argument 를 보내지 않을 때는 anonymous 유저에게 "hello" 라고 하는 문장을 출력해보자
# say_hello("KARINA") 에서 KARINA 로 user_name 에 전달하면 hello KARINA 라고 출력된다
# say_hello() 에서 () 에 name 이 없을 땐 anonymous 로 출력되게 만들어본다

def say_hello(user_name=):
  print("hello", user_name)

say_hello("KARINA")      # KARINA 로 user_name 에 전달하면 hello KARINA 라고 출력된다
say_hello()              # () 에 name 이 없을 땐 anonymous 로 출력되게 만들어본다

